aliases: []
creation_timestamp: 1700649259576
current_stage: None
description: null
last_updated_timestamp: 1700649259576
name: rf_regressor
run_id: bd8ae8545a2e401ba0be153ba21ff881
run_link: null
source: file:///home/makar/mlruns/3/bd8ae8545a2e401ba0be153ba21ff881/artifacts/rf_regressor
status: READY
status_message: null
storage_location: file:///home/makar/mlruns/3/bd8ae8545a2e401ba0be153ba21ff881/artifacts/rf_regressor
user_id: null
version: 4
