aliases: []
creation_timestamp: 1700573013603
current_stage: None
description: null
last_updated_timestamp: 1700573013603
name: rf_regressor
run_id: e8db979386b64c058997b5c4c105f66f
run_link: null
source: file:///home/makar/mlruns/3/e8db979386b64c058997b5c4c105f66f/artifacts/rf_regressor
status: READY
status_message: null
storage_location: file:///home/makar/mlruns/3/e8db979386b64c058997b5c4c105f66f/artifacts/rf_regressor
user_id: null
version: 2
