aliases: []
creation_timestamp: 1700650310846
current_stage: None
description: null
last_updated_timestamp: 1700650310846
name: rf_regressor
run_id: 5b1e09a4e26b4d78a823920747e4fac8
run_link: null
source: file:///home/makar/mlruns/3/5b1e09a4e26b4d78a823920747e4fac8/artifacts/rf_regressor
status: READY
status_message: null
storage_location: file:///home/makar/mlruns/3/5b1e09a4e26b4d78a823920747e4fac8/artifacts/rf_regressor
user_id: null
version: 10
